services:
  mongo:
    image: mongo:7-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: restriction
      MONGO_INITDB_USERNAME: myuser
      MONGO_INITDB_PASSWORD: mypassword
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  mongo_data: